# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7587a43a71d42b43d60355d60b3e21ab9e62be46920f06b6092a156aa98ddee875a875729a29c2b385eb5ecc04819233d7a0f70153f9603ecdff8bd41de3e573

test:
  secret_key_base: ef67f2ffa9bcfc3657fd27951a6792eb3563b33014ecd6227e74f9a50f3549523a0bf717ef0806ccd75b2627c9dfa533997c801d23d6144437609a522a06fca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 7587a43a71d42b43d60355d60b3e21ab9e62be46920f06b6092a156aa98ddee875a875729a29c2b385eb5ecc04819233d7a0f70153f9603ecdff8bd41de3e573
